# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
{{- if .Values.egressFilter.oauth2Secret }}
apiVersion: v1
kind: Secret
metadata:
  name: runtime-networking-filter.oauth2
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range $key, $val := .Values.egressFilter.oauth2Secret }}
  {{ $key }}: {{ b64enc $val }}
{{- end }}
{{- end }}